---
title: "Diagnosis Analysis"
author: "Ryan Hawkins"
date: "January 12, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(scales)
```

##Data Import

Read in the data

```{r}
claimsFull <- readRDS("Data/claimsCleanFull.RDS")
```

##Factor Levels

Check out the levels of all factor variables

```{r}
claimsFull %>%
  select_if(is.factor) %>%
  map(nlevels) %>%
  unlist()
```

```{r}
# Select the most important columns
claims <- claimsFull %>%
  select(MRN_ALIAS, MEMBER_SEX,MEMBER_AGE,CLAIM_SEQ,EPISODE_SEQ,APPROVED_AMT,
APPROVED_DAYS,CODE_1, CODE_2,  ED_DISCHARGE_DX_DESC,PREVENTABILITY,ED_NOT_NEEDED_PROP,
UNCLASSIFIED_ED, PCP_ID, VENDOR_PROV_ID, SERVICE_TYPE,CLAIM_TYPE,
PLACE_OF_SERVICE_DESC, TOB_CATEGORY,YEAR) %>%
  arrange(MRN_ALIAS, CLAIM_SEQ, EPISODE_SEQ)

# Get rid of full data set to save on memory.
rm(claimsFull)

# Glimspe at the structure of claims
glimpse(claims)

# View summary of columns, takes some time to run
summary(claims)
```


###Looking at CODES and DIAGNOIS

```{r}
diag <-claims %>% 
  select(ED_DISCHARGE_DX_DESC, CODE_1, ED_NOT_NEEDED_PROP, PREVENTABILITY) %>% 
  mutate(CODE_P = gsub("\\..*","",claims$CODE_1)) %>% 
  group_by(ED_DISCHARGE_DX_DESC, CODE_1, CODE_P)%>%
  summarize(ED_NOT_NEEDED_PROP = mean(ED_NOT_NEEDED_PROP), PREVENTABILITY = mean(PREVENTABILITY),
n = n())

write.csv(diag, "diagnosis codes.csv")
```


```{r}
claims$CODE_1 <- as.character(claims$CODE_1)
str(diag)

claims$CODE_P <- gsub("\\..*","",claims$CODE_1)

d.group <-claims %>% select(ED_DISCHARGE_DX_DESC,CODE_P, ED_NOT_NEEDED_PROP, PREVENTABILITY) %>% 
  group_by(CODE_P, ED_NOT_NEEDED_PROP, PREVENTABILITY) %>% 
  summarize(n = n())


diag$CODE_1 <- as.character(diag$CODE_1)
str(diag)

daig$CODE_P <- gsub("\\..*","",diag$CODE_1)

d.group.unique <-diag %>% select(CODE_P, ED_NOT_NEEDED_PROP, PREVENTABILITY) %>% 
  group_by(CODE_P, ED_NOT_NEEDED_PROP, PREVENTABILITY) %>% 
  summarize(n = n())

```

