---
title: "Untitled"
author: "Ryan Hawkins"
date: "November 7, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(scales)
```

```{r}
movie_profit_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-10-23/movie_profit.csv")

```

```{r}
movie_profit <- movie_profit_raw %>% 
  select(-X1) %>% 
  mutate(release_date = as.Date(parse_date_time(release_date, "%m!/%d/%Y"))) %>% 
  filter(release_date < "2018-09-01") %>% 
  mutate(distributor = fct_lump(distributor,6))
```


```{r}
movie_profit %>% 
  ggplot(aes(production_budget)) +
  geom_histogram()+
  scale_x_log10(labels = dollar_format()) 
```

###What genres make the most money?

```{r}

movie_profit %>% 
  mutate(genre = fct_reorder(genre, production_budget)) %>% 
  filter(!is.na(distributor)) %>% 
  ggplot(aes(genre,production_budget)) +
  geom_boxplot()+
  scale_y_log10(labels = dollar_format()) +
  coord_flip() +
  facet_wrap(~ distributor)

```

What are typical budgests over time

```{r}
movie_profit %>% 
  mutate(decade = 10 * floor(year(release_date)/10)) %>% 
  group_by(decade) %>% 
  summarize_at(vars(production_budget:worldwide_gross), median, na.rm = TRUE) %>% 
  gather(metric, value, -decade ) %>% 
  ggplot(aes(decade,value, color = metric)) +
  geom_line() +
  scale_y_continuous(labels = dollar_format())
```

